import { bitfield, prim, wchar, type StructDef } from '../types.js';

const FACE_FLAGS = bitfield({
  name: 'FaceFlags',
  members: [
    { name: 'unknown', bits: 1 },
    { name: 'bangsSide', bits: 1 },
    { name: 'backDualColor', bits: 1 },
    { name: 'bangsDualColor', bits: 1 },
    { name: 'eyeShadowEnabled', bits: 1 },
    { name: 'mouthInvert', bits: 1 },
    { name: 'mustacheInverted', bits: 1 },
    { name: 'moleHigh', bits: 1 },
  ],
});

const HAIR_STYLE_FLAGS = bitfield({
  name: 'HairStyleFlags',
  members: [
    { name: 'leftSide', bits: 1 },
    { name: 'rightSide', bits: 1 },
    { name: 'reserved', bits: 6 },
  ],
});

const u8 = prim('u8');

export const CHAR_INFO_EX: StructDef = {
  name: 'CharInfoEx',
  fields: [
    { name: 'createId1', type: prim('s32') },
    { name: 'createId2', type: prim('s32') },
    { name: 'createId3', type: prim('s32') },
    { name: 'createId4', type: prim('s32') },
    { name: 'name', type: wchar(11) },
    { name: 'fontRegion', type: u8 },
    { name: 'gender', type: prim('u8', ['Male', 'Female']) },
    { name: 'height', type: u8 },
    { name: 'build', type: u8 },
    { name: 'regionMove', type: u8 },
    { name: 'faceFlags', type: FACE_FLAGS },
    { name: 'facelineType', type: u8 },
    { name: 'facelineColor', type: u8 },
    { name: 'wrinkleLowerType', type: u8 },
    { name: 'wrinkleLowerScale', type: u8 },
    { name: 'wrinkleLowerAspect', type: u8 },
    { name: 'wrinkleLowerX', type: u8 },
    { name: 'wrinkleLowerY', type: u8 },
    { name: 'wrinkleUpperType', type: u8 },
    { name: 'wrinkleUpperScale', type: u8 },
    { name: 'wrinkleUpperAspect', type: u8 },
    { name: 'wrinkleUpperX', type: u8 },
    { name: 'wrinkleUpperY', type: u8 },
    { name: 'makeup0', type: u8 },
    { name: 'makeup0Color', type: u8 },
    { name: 'makeup0Scale', type: u8 },
    { name: 'makeup0Aspect', type: u8 },
    { name: 'makeup0X', type: u8 },
    { name: 'makeup0Y', type: u8 },
    { name: 'makeup1', type: u8 },
    { name: 'makeup1Color', type: u8 },
    { name: 'makeup1Scale', type: u8 },
    { name: 'makeup1Aspect', type: u8 },
    { name: 'makeup1X', type: u8 },
    { name: 'makeup1Y', type: u8 },
    { name: 'hairType', type: prim('u16') },
    { name: 'hairColor0', type: u8 },
    { name: 'hairColor1', type: u8 },
    { name: 'hairTypeFront', type: u8 },
    { name: 'hairTypeBack', type: u8 },
    { name: 'hairStyle', type: HAIR_STYLE_FLAGS },
    { name: 'earType', type: u8 },
    { name: 'earScale', type: u8 },
    { name: 'earY', type: u8 },
    { name: 'eyeType', type: u8 },
    { name: 'eyeColor', type: u8 },
    { name: 'eyeScale', type: u8 },
    { name: 'eyeAspect', type: u8 },
    { name: 'eyeRotate', type: u8 },
    { name: 'eyeX', type: u8 },
    { name: 'eyeY', type: u8 },
    { name: 'eyeShadowColor', type: u8 },
    { name: 'eyeHighlightType', type: u8 },
    { name: 'eyeHighlightScale', type: u8 },
    { name: 'eyeHighlightAspect', type: u8 },
    { name: 'eyeHighlightRotate', type: u8 },
    { name: 'eyeHighlightX', type: u8 },
    { name: 'eyeHighlightY', type: u8 },
    { name: 'eyelashUpperType', type: u8 },
    { name: 'eyelashUpperScale', type: u8 },
    { name: 'eyelashUpperAspect', type: u8 },
    { name: 'eyelashUpperRotate', type: u8 },
    { name: 'eyelashUpperX', type: u8 },
    { name: 'eyelashUpperY', type: u8 },
    { name: 'eyelashLowerType', type: u8 },
    { name: 'eyelashLowerScale', type: u8 },
    { name: 'eyelashLowerAspect', type: u8 },
    { name: 'eyelashLowerRotate', type: u8 },
    { name: 'eyelashLowerX', type: u8 },
    { name: 'eyelashLowerY', type: u8 },
    { name: 'eyelidUpperType', type: u8 },
    { name: 'eyelidUpperScale', type: u8 },
    { name: 'eyelidUpperAspect', type: u8 },
    { name: 'eyelidUpperRotate', type: u8 },
    { name: 'eyelidUpperX', type: u8 },
    { name: 'eyelidUpperY', type: u8 },
    { name: 'eyelidLowerType', type: u8 },
    { name: 'eyelidLowerScale', type: u8 },
    { name: 'eyelidLowerAspect', type: u8 },
    { name: 'eyelidLowerRotate', type: u8 },
    { name: 'eyelidLowerX', type: u8 },
    { name: 'eyelidLowerY', type: u8 },
    { name: 'eyebrowType', type: u8 },
    { name: 'eyebrowColor', type: u8 },
    { name: 'eyebrowScale', type: u8 },
    { name: 'eyebrowAspect', type: u8 },
    { name: 'eyebrowRotate', type: u8 },
    { name: 'eyebrowX', type: u8 },
    { name: 'eyebrowY', type: u8 },
    { name: 'noseType', type: u8 },
    { name: 'noseScale', type: u8 },
    { name: 'noseY', type: u8 },
    { name: 'mouthType', type: u8 },
    { name: 'mouthColor', type: u8 },
    { name: 'mouthScale', type: u8 },
    { name: 'mouthAspect', type: u8 },
    { name: 'mouthRotate', type: u8 },
    { name: 'mouthY', type: u8 },
    { name: 'beardType', type: u8 },
    { name: 'beardColor', type: u8 },
    { name: 'beardShortType', type: u8 },
    { name: 'beardShortColor', type: u8 },
    { name: 'mustacheType', type: u8 },
    { name: 'mustacheColor', type: u8 },
    { name: 'mustacheScale', type: u8 },
    { name: 'mustacheAspect', type: u8 },
    { name: 'mustacheY', type: u8 },
    { name: 'glassType1', type: u8 },
    { name: 'glassColor1', type: u8 },
    { name: 'glassScale', type: u8 },
    { name: 'glassAspect', type: u8 },
    { name: 'glassY', type: u8 },
    { name: 'glassType2', type: u8 },
    { name: 'glassColor2', type: u8 },
    { name: 'moleScale', type: u8 },
    { name: 'moleX', type: u8 },
    { name: 'moleY', type: u8 },
    { name: 'unkDefault45', type: u8 },
  ],
};
